name = "leaveit"
license = "MIT"
licenselink = "https://github.com/amrom66/leaveit/blob/main/LICENSE"
description = "A simple, clean blog theme for hugo."
homepage = "https://blog.amrom.tk"
tags = [
  "blog",
  "minimal",
  "clean",
  "responsive",
  "gallery",
  "dark",
  "theme"
]
features = [
  "cover-image",
  "favicon",
  "multilingual",
  "pagination",
  "social-menu",
  "syntax-highlighting",
]
min_version = "0.41"

[author]
  name = "amrom"
  homepage = "https://blog.amrom.tk"
[params]
  home_mode = "post"